apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - name: springbootapp
          image: __IMAGE__@__DIGEST__
          ports:
            - name: 9080-tcp
              containerPort: 9080
              protocol: TCP
            - name: 9443-tcp
              containerPort: 9443
              protocol: TCP
            - name: http
              containerPort: 9082
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  ports:
    - name: 9080-tcp
      port: 9080
      targetPort: 9080
      protocol: TCP
    - name: 9443-tcp
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: http
      port: 9082
      protocol: TCP
      targetPort: 9082
  selector:
    app: springbootapp
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  port:
    targetPort: 9080-tcp
  to:
    kind: Service
    name: springbootapp
    weight: 100
