apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - name: springbootapp
          image: __IMAGE__@__DIGEST__
          ports:
            - name: http-server
              containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  ports:
    - port: 9080
      targetPort: http-server
  selector:
    app: springbootapp
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  port:
    targetPort: 9080
  to:
    kind: Service
    name: springbootapp
    weight: 100